src/Codeception/Lib/Connector/Yii2.php
src/Codeception/Module/Yii2.php

See #2 
Validated locally with a functional test written before this (admin user uploads a file, non-admin user sees the uploaded file, admin removes the file).

Module implements Codeception's MultiSession

---

src/Codeception/Module/Yii2.php

https://codeception.com/docs/modules/Yii2
`transaction - (default: true) `

Codeception documentation specified this is true

---

src/Codeception/Module/Yii2.php

When haveRecord is used and it fails to create a model due to some validation, it's not obvious from the test output why.
The proposed fix will append default failure message with associated validation errors

Validation errors for haveRecord method

---

src/Codeception/Module/Yii2.php

With a Docker standalone ChromeDriver setup, I am running into issues with $_SESSION being undefined in the backup function - $_COOKIE is fine in the setup but adding a check on that line for consistency. I also noticed that the ModuleException signature requires a second parameter - fixing while I'm in this section.

Fix ModuleException parameters, handle undefined

---

src/Codeception/Lib/Connector/Yii2.php

Initialize the $_SERVER['QUERY_STRING'] variable, to mimic normal behavior of most webservers.

Initialize $_SERVER['QUERY_STRING']

---

.github/workflows/main.yml
composer.json

See https://github.com/Codeception/module-yii2/issues/17

Allow installing on PHP 8

---

src/Codeception/Lib/Connector/Yii2.php

Using createObject with \yii\di\Instance::of in configuration does not work.
Creating an instance of the application in the suggested way solves the problem.

Fix for support Instance::of in configuration

---

src/Codeception/Lib/Connector/Yii2.php
src/Codeception/Module/Yii2.php

As I was testing an application, I realized that it is impossible to change the application class without creating extra config files. By checking the code, I saw that it should be possible to determine the application class by setting a root level `class` key in the application config file (e.g. `common/config/test.php`). The issue with that is `yii_test` is loading this config file as well and get a `yii\base\UnknownPropertyException` with the message 'Setting unknown property: yii\console\Application::class'.
So either you modify `yii_test` to unset the class key before creating the console application or create another config file just for codeception and define the class there.
Thus I felt, it would be more sensible to have this configuration value in the codeception module itself.

Application class config

---

src/Codeception/Module/Yii2.php

The pull request as discussed on #42 
Also I fixed one documentation issue, my IDE highlighted several more but for that one I was certain that it would not have any side effects.
And again, I would highly appreciate getting the `hacktoberfest-accepted` label :)

Annotate throws with FQN

---

composer.json

fix codeception/module-yii2 1.1.4 requires php >=5.6.0 <=8.1 -> your php version (8.1.1) does not satisfy that requirement

fix install on php8.1.1

---

.github/workflows/main.yml
.gitignore
composer.json
src/Codeception/Lib/Connector/Yii2.php
src/Codeception/Lib/Connector/Yii2/FixturesStore.php
src/Codeception/Module/Yii2.php
tests/bootstrap.php
tests/cases/closeConnections/codeception.yml
tests/cases/closeConnectionsNoCleanup/codeception.yml
tests/cases/events/codeception.yml
tests/cases/events/functional/ResponseCest.php
tests/cases/locale-urls/codeception.yml
tests/cases/locale-urls/functional/LocaleUrlCest.php
tests/cases/mock-mailer/codeception.yml
tests/cases/mock-mailer/functional/MockMailerCest.php
tests/cases/pageCacheHeaderAlreadySent/codeception.yml
tests/cases/pageCacheHeaderAlreadySent/functional/PageCest.php
tests/cases/simple/codeception.yml
tests/cases/simple/functional.suite.yml
tests/cases/simple/functional/SimpleCest.php
tests/cases/sqlite/codeception.yml
tests/cases/yii2-app-advanced/codeception.yml

All tests pass. 
Changes to yii2-advanced-template are required and are not breaking changes. So I will submit a PR to that repo shortly - this PR is here https://github.com/yiisoft/yii2-app-advanced/pull/518
Once this and the above pull requests are accepted this module is good to go with Codecept V5 and PHP 8.1

Compatibility with Codeception 5 and PHP 8.1

---

src/Codeception/Module/Yii2.php

Fix warning:
```shell
Warning: array_merge() expects at least 1 parameter, 0 given
```
Inside test (empty `_fixtures()`):
```php
$this->tester->grabFixture('some');
```

Fix warning

---

src/Codeception/Module/Yii2.php

Fix last commit error:
```shell
Exception 'Error' with message 'Call to a member function getAndClearLog() on null' in /srv/www/app/vendor/codeception/module-yii2/src/Codeception/Module/Yii2.php:400
Stack trace:
#0 /srv/www/app/vendor/codeception/codeception/src/Codeception/Subscriber/Module.php(90): Codeception\Module\Yii2-&gt;_failed(Object(Codeception\Test\TestCaseWrapper), Object(PHPUnit\Framework\ExpectationFailedException))
#1 /srv/www/app/vendor/symfony/event-dispatcher/EventDispatcher.php(230): Codeception\Subscriber\Module-&gt;failed(Object(Codeception\Event\FailEvent), 'test.fail', Object(Symfony\Component\EventDispatcher\EventDispatcher))
...
```

Fix last commit error

---

src/Codeception/Lib/Connector/Yii2.php

Sometimes Psalm finds a floating bug on some systems:
```
message: Class, interface or enum Yii\web\ErrorAction has wrong casing
type: InvalidClass
snippet: 'class' => yii\web\ErrorAction::class,
selected_text: yii\web\ErrorAction
```
This PR should fix the floating bug with yii\web* napespace.

Fix wrong namespace

---

src/Codeception/Module/Yii2.php

This will help me fix my PHPStan integration :crossed_fingers:

Use correct type declaration for amOnPage method

---

src/Codeception/Lib/Connector/Yii2/FixturesStore.php

There is an issue configuring component properties when the user does not use Yii2 default values during Codeception tests. The problem caused by using anonymous array value to register InitDbFixture [yii\test\InitDbFixture] component rather than using key-pair component registering.
The following attachment occurred from changing Yii default database component from `db` to something else.
During FixturesStore [Codeception\Lib\Connector\Yii2\FixturesStore] initialization, its `globalFixtures()` has InitDbFixture component registering as anonymous fixture value resulting to Yii unable to merge the fixtures array in FixtureTrait [yii\test\FixtureTrait::getFixtures()].
By changing its registration from the following
```php
return [
InitDbFixture::class
];
```
to
```php
return [ …
```

InitDbFixture object cannot be overridden during FixturesStore initialization

---

src/Codeception/Module/Yii2.php

When using `$I->haveFriend()`, my tests would fail with the following error.
```
[yii\base\UnknownPropertyException] Getting unknown property: yii\console\Application::session
```
This is because the code in `_backupSession()` didn't check if we actually have a `Yii::$app->session` before accessing `Yii::$app->session->useCustomStorage`.
This PR fixes this and allows me to run my tests.
See #2 and #3

Fix parallel sessions with `$I->haveFriend()` when no session is active

---

.github/workflows/main.yml
composer.json
phpstan.neon
src/Codeception/Lib/Connector/Yii2.php
src/Codeception/Lib/Connector/Yii2/ConnectionWatcher.php
src/Codeception/Lib/Connector/Yii2/Logger.php
src/Codeception/Lib/Connector/Yii2/TransactionForcer.php
src/Codeception/Module/Yii2.php
tests/Yii.stub

This PR improves typing and fixes issues identified by phpstan.
It also removes some functions that were already marked as `@internal` (so it doesn't count as breaking backward compatibility)

Improved typing

---

src/Codeception/Lib/Connector/Yii2.php

Recent changes ([here](https://github.com/Codeception/module-yii2/commit/219fbd9465472077785e1a93fc01fa89489bf2cc#diff-73a2f17bdda413759cc20c4cdd039997604a9bf4cc857283d0e71d8ec6982dfaL137-R137)) introduced that bug. The newly added `$user` variable for checking if `User` component is of the right type overwrites the parameter to the method with the same name.

Fix broken `amLoggedInAs` - method parameter is being overwritten

---

.github/workflows/main.yml
src/Codeception/Lib/Connector/Yii2.php
src/Codeception/Module/Yii2.php

Implicitly nullable parameter types are deprecated: https://wiki.php.net/rfc/deprecate-implicitly-nullable-types

Fix PHP 8.4 deprecation warnings

---

src/Codeception/Lib/Connector/Yii2.php
src/Codeception/Lib/Connector/Yii2/ConnectionWatcher.php
src/Codeception/Lib/Connector/Yii2/FixturesStore.php
src/Codeception/Lib/Connector/Yii2/Logger.php
src/Codeception/Lib/Connector/Yii2/TestMailer.php
src/Codeception/Lib/Connector/Yii2/TransactionForcer.php
src/Codeception/Module/Yii2.php
tests/cases/closeConnections/fixtures/EmptyFixture.php
tests/cases/closeConnections/functional/FixturesCest.php
tests/cases/closeConnections/functional/FixturesInBeforeCest.php
tests/cases/closeConnections/functional/NoFixturesCest.php
tests/cases/closeConnections/helpers/SqlliteHelper.php
tests/cases/closeConnectionsNoCleanup/functional/FixturesCest.php
tests/cases/closeConnectionsNoCleanup/functional/FixturesInBeforeCest.php
tests/cases/closeConnectionsNoCleanup/functional/ThirdCest.php
tests/cases/events/controllers/SiteController.php
tests/cases/events/functional/ResponseCest.php
tests/cases/locale-urls/controllers/SiteController.php
tests/cases/locale-urls/functional/LocaleUrlCest.php
tests/cases/mock-mailer/controllers/SiteController.php
tests/cases/mock-mailer/functional/MockMailerCest.php
tests/cases/pageCacheHeaderAlreadySent/controllers/UserController.php
tests/cases/pageCacheHeaderAlreadySent/functional/PageCest.php
tests/cases/simple/controllers/SiteController.php
tests/cases/simple/functional/SimpleCest.php
tests/cases/simple/helpers/DummyUser.php
tests/cases/simple/helpers/EmptyString.php
tests/cases/sqlite/fixtures/TestFixture.php
tests/cases/sqlite/functional/SqLiteCest.php

I also replace `assertEquals` with `assertSame`

Add strict types

---

composer.json
phpstan.neon
src/Codeception/Lib/Connector/Yii2.php
src/Codeception/Lib/Connector/Yii2/ConnectionWatcher.php
src/Codeception/Lib/Connector/Yii2/FixturesStore.php
src/Codeception/Lib/Connector/Yii2/Logger.php
src/Codeception/Lib/Connector/Yii2/TestMailer.php
src/Codeception/Lib/Connector/Yii2/TransactionForcer.php
src/Codeception/Module/Yii2.php

I am not a regular user of Yii, please review critically.

Implement new PHP features up to 8.0

---

src/Codeception/Module/Yii2.php

This removes multi session support since it is broken (#114), and cannot reasonably be fixed given Yii's constraints.
This will be part of next major release.
Edit: this will only be merged after the CS changes are merged; so for review only review this commit: https://github.com/Codeception/module-yii2/pull/124/commits/8c6b44b5511e15b4ff96a7b15e376beb00f8b0a3

Remove multi session
